# Cách đọc tạp chí này // How to read this zine {-}

Cuốn sách này có tiếng Việt (trang 4-19) và tiếng Anh (trang 22-37). 

Cuốn sách này là một câu chuyện với Kết Thúc Tự Chọn. Điều này có nghĩa là từ trang 15-19 (tiếng Việt) và trang 33-37 (tiếng Anh) bạn có thể quyết định số phận của các nhân vật và xem cái kết mình mong muốn. Ví dụ, nếu bạn chọn kết thúc #2 bạn sẽ phải sang trang 17 để đọc kết thúc tương ứng. Chúng tôi mong bạn sẽ xem lại từng cái kết để xem những hướng khác nhau mà câu chuyện có thể đi tới.

Câu chuyện này được dựa trên nghiên cứu khoa học. Vui lòng chia sẻ những suy nghĩ, phản hồi, và kinh nghiệm của bạn tại https://bit.ly/viet-zine-survey

Tác giả (theo thứ tự bảng chữ cái): Celestine Le, Rachel Moran, Anh Nguyen, và Sarah Nguyễn 
Hoạ sĩ minh hoạ: Anh Nguyen 
Dịch giả: Trung-Anh Nguyen 
Biên tập viên: Nguyên Lê, Hoàng Kim Nguyễn, và Kenney Tran

---

This book available in both Vietnamese (pages 4 - 19) and English (pages 22-37). 

This book is a Choose-Your-Own-Adventure story. This means from pages 13-18 (Vietnamese) and pages 33-37 (English) you can decide the characters' fates and choose which ending you want to experience. For example, if you choose ending #2 you will have to flip to page 35 to read the corresponding ending. We encourage you to revisit each ending to see the different ways the story could go. 

This story is based off of empirical research. Please Share your reflections, feedback, and experiences at https://bit.ly/viet-zine-survey

Authors (alphabetical order): Celestine Le, Rachel Moran, Anh Nguyen, and Sarah Nguyễn
Graphic artist: Anh Nguyen
Translator: Trung-Anh Nguyen
Copy editor: Nguyên Lê, Hoàng Kim Nguyễn, and Kenney Tran
